# 必须使用video_player_web开头，否则注册不会生效
# 原理是必须要将本组件的registerWith排在videoplayer后面
name: video_player_web_hls_swarm_cloud
description: A fork of video_player_web_hls to support hls settings.
homepage: https://github.com/swarm-cloud/flutter-p2p-engine-plus
# 0.1.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 0.3.0

flutter:
  plugin:
    implements: video_player
    platforms:
      android:
        default_package: video_player_android
      ios:
        default_package: video_player_avfoundation
      web:
        pluginClass: SwarmVideoPlayerPluginHls 
        fileName: swarm_cloud_video_player_hls.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.3
  meta: ^1.3.0
  video_player_platform_interface: ">=4.2.0 <6.0.0"
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"